# This file contains values from Cookiecutter

default_context:
  project_name: "snyk-to-azure-boards"
  project_description: "CLI tool to convert Snyk issues to Azure Boards issues."
  organization: "snyk"
  license: "Apache Software License 2.0"
  minimal_python_version: 3.9
  github_name: "writingpanda"
  email: "omar.quimbaya@snyk.io"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
